inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Layout/IndentHeredoc:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Exclude:
    - 'Gemfile'

Layout/TrailingWhitespace:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'
